### ISSUE TITLE
Skip to specified page

### ISSUE THREAD

**Issue by sethchhim** [mertakdut/EpubParser#10]
Is there an easy way to skip to a specific page?

I have tried:
`int customPageNumber = 25;`
`mViewPager.setAdapter(mSectionsPagerAdapter);`
`mViewPager.setCurrentItem(customPageNumber);`

but I get a strange bug where the next few pages are repeats. My goal is to create a bookmark effect by manually inserting the desired page number.

Tested on the sample application.

Also:
`mViewPager.setOffscreenPageLimit(0);`
outputs this message:
`W/ViewPager: Requested offscreen page limit 0 too small; defaulting to 1`

**Comment by mertakdut** [comment]
This is currently not possible. Library is meant to proceed sequentially.

But I am willing to add that functionality in the future. With the saving progress functionality.

**Comment by sethchhim** [comment]
Looking forward to it and thanks for the quick response.

**Comment by mertakdut** [comment]
Let the issue stay opened. This and progress-saving functionalities are must :)

**Comment by mertakdut** [comment]
Skipping to specified page is now available. Please let me know if there is any issue. 

You can also check the functionality on [sample application](https://github.com/mertakdut/EpubParser-Sample-Android-Application).
