### ISSUE TITLE
how to get the table of contents as list

### ISSUE THREAD

**Issue by kiyos88** [mertakdut/EpubParser#15]

**Comment by mertakdut** [comment]
Hello,

With this, you can reach all the navigation points in the toc.ncx file:
`reader.getToc().getNavMap().getNavPoints();`

Just make sure you called _setFullContent_ first.

**Comment by mertakdut** [comment]
Though, keep in mind that navigation points may dynamically change as you move through the book. The result of _getNavPoints_ method will most probably be different when you call it after the _setFullContent_ than after you progressed in the book.
