### ISSUE TITLE
please add a constructor for java.io.File

### ISSUE THREAD

**Issue by eimhee** [mertakdut/EpubParser#18]
please change the method setFullContent to support java.io.File, thanks.

Reader reader = new Reader();
reader.setMaxContentPerSection(1000); // Max string length for the current page.
reader.setIsIncludingTextContent(true); // Optional, to return the tags-excluded version.
reader.setFullContent(new File(epubFilePath)); // Must call before readSection.

**Comment by mertakdut** [comment]
Sure thing. 

But just for the sake of curiosity, why do you need another constructor? Can't you just use the current one with file.getPath()? What would be the difference? I might be missing a point, didn't think of it throughly.

**Comment by mertakdut** [comment]
This still looks redundant to me since I didn't get any explanation.

You could just call file.getAbsolutePath and send the path.
