### ISSUE TITLE
Recursive call to fillNavPoints overwrites "this.navPoints"

### ISSUE THREAD

**Issue by scorpionjacky** [mertakdut/EpubParser#19]
At the beginning of fillNavPoints function, the following statement clears all previously generated navPoints if this is a recursive call:

_this.navPoints = new ArrayList<>();_

Recursive call of fillNavPoints happens when there are more than one level of TOC.

**Comment by mertakdut** [comment]
You are absolutely right. I've totally forgot about nested navPoints when I changed the navPoints initialization way.

Adding null control before instantiating navPoints.

Thank you for your participation.
