### ISSUE TITLE
opf:guide did not load

### ISSUE THREAD

**Issue by epubreader** [mertakdut/EpubParser#22]
opf:guide did not load, when the node name is "opf:guide", 
I think you change equals to endwiths method

`
   boolean fillContent(Node node) throws ReadingException {
        if(node.getNodeName().equals("metadata")) {
            this.getMetadata().fillAttributes(node.getChildNodes());
            this.isMetadataFound = true;
        } else if(node.getNodeName().equals("manifest")) {
            this.getManifest().fillXmlItemList(node.getChildNodes());
            this.isManifestFound = true;
        } else if(node.getNodeName().equals("spine")) {
            this.getSpine().fillXmlItemList(node.getChildNodes());
            this.isSpineFound = true;
        } else if(node.getNodeName().equals("guide")) {
            this.getGuide().fillXmlItemList(node.getChildNodes());
            this.isGuideFound = true;
        }

        return this.isMetadataFound && this.isManifestFound && this.isSpineFound && this.isGuideFound;
    }
`
`
<?xml version="1.0"  encoding="UTF-8"?>
<opf:package xmlns:opf="http://www.idpf.org/2007/opf" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcms="http://www.dcms.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" unique-identifier="bookid" version="3.0">
   <opf:metadata>
      <dc:creator opf:role="aut" opf:file-as="Sussman, Jeffrey">Jeffrey Sussman</dc:creator>
<dc:title>Max Baer and Barney Ross</dc:title>
      <dc:description>In the 1920s and 30s, anti-Semitism was rife in the United States and Europe. Jews needed symbols of strength and demonstrations of courage against their enemies, and they found both in two champions of boxing: Max Baer and Barney Ross. Baer was the only Jewish heavyweight champion in the twentieth century, while Ross was considered one of the greatest welterweight and lightweight champions of the era. Although their careers never crossed paths, their boxing triumphs played a common role in lifting the spirits of persecuted Jews.&lt;br /&gt;In Max Baer and Barney Ross: Jewish Heroes of Boxing, Jeffrey Sussman chronicles the lives of two men whose successful bouts inside the ring served as inspiration for Jewish fans across the country and around the world. Though they came from very different backgrounds&amp;#8212;Baer grew up on his family's ranch in California, while Ross roamed the tough streets of Chicago and was a runner for Al Capone&amp;#8212;both would bask in the limelight as boxing...</dc:description>
      <dc:publisher>Rowman &amp; Littlefield Publishers</dc:publisher>
      <dc:date>2012-04-18T23:00:00+00:00</dc:date>
      <opf:meta property="dcterms:modified">
			2012-04-12T12:00:00Z
		</opf:meta>
      <dc:identifier id="bookid">
			urn:isbn:undefined</dc:identifier>
      <dc:rights>undefined</dc:rights>
      <dc:coverage>undefined</dc:coverage>
      <opf:meta name="cover" content="cover-image"/>
   <meta xmlns="http://www.idpf.org/2007/opf" name="calibre:title_sort" content="Max Baer and Barney Ross"/>
<dc:subject xmlns="http://www.idpf.org/2007/opf">undefined</dc:subject>
<dc:contributor xmlns="http://www.idpf.org/2007/opf" opf:role="bkp">calibre (2.50.0) [http://calibre-ebook.com]</dc:contributor>
<meta xmlns="http://www.idpf.org/2007/opf" name="calibre:author_link_map" content="{&quot;Jeffrey Sussman&quot;: &quot;&quot;}"/>
<dc:language xmlns="http://www.idpf.org/2007/opf">en-US</dc:language>
<dc:identifier xmlns="http://www.idpf.org/2007/opf" opf:scheme="calibre">b2fc722a-91da-47fe-a8dc-f52748dcc098</dc:identifier>
</opf:metadata>
   <opf:manifest>
      <opf:item href="toc.ncx" id="ncx" media-type="application/x-dtbncx+xml"/>
      <opf:item href="toc_nav.xhtml" id="nav" media-type="application/xhtml+xml" properties="nav"/>
      <opf:item href="1-A01-Rowman_frontmatter.xhtml" id="frontmatter" media-type="application/xhtml+xml"/>
      <opf:item href="1-A01-Rowman_cover.xhtml" id="cover" media-type="application/xhtml+xml"/>
      <opf:item href="css/xml2epub.css" id="css-file" media-type="text/css"/>
      <opf:item href="3-B02-acknowledgments.xhtml" id="d44e9" media-type="application/xhtml+xml"/>
      <opf:item href="4-B03-introduction.xhtml" id="d44e11" media-type="application/xhtml+xml"/>
      <opf:item href="5-C01-chap01.xhtml" id="d44e13" media-type="application/xhtml+xml"/>
      <opf:item href="6-C02-chap02.xhtml" id="d44e16" media-type="application/xhtml+xml"/>
      <opf:item href="7-C03-chap03.xhtml" id="d44e18" media-type="application/xhtml+xml"/>
      <opf:item href="8-C04-chap04.xhtml" id="d44e20" media-type="application/xhtml+xml"/>
      <opf:item href="9-C05-chap05.xhtml" id="d44e22" media-type="application/xhtml+xml"/>
      <opf:item href="10-C06-chap06.xhtml" id="d44e24" media-type="application/xhtml+xml"/>
      <opf:item href="11-C07-chap07.xhtml" id="d44e26" media-type="application/xhtml+xml"/>
      <opf:item href="12-C08-chap08.xhtml" id="d44e29" media-type="application/xhtml+xml"/>
      <opf:item href="13-C09-chap09.xhtml" id="d44e31" media-type="application/xhtml+xml"/>
      <opf:item href="14-C10-chap10.xhtml" id="d44e33" media-type="application/xhtml+xml"/>
      <opf:item href="15-D01-appendixA.xhtml" id="d44e35" media-type="application/xhtml+xml"/>
      <opf:item href="16-D02-appendixB.xhtml" id="d44e37" media-type="application/xhtml+xml"/>
      <opf:item href="17-D03-bibliography.xhtml" id="d44e39" media-type="application/xhtml+xml"/>
      <opf:item href="18-I01-index.xhtml" id="d44e42" media-type="application/xhtml+xml"/>
      <opf:item href="19-J01-author.xhtml" id="d44e43" media-type="application/xhtml+xml"/>
      <opf:item href="images/27-F06.tif.jpg" id="d64e3" media-type="image/jpeg"/>
      <opf:item href="images/25-F04.tif.jpg" id="d64e5" media-type="image/jpeg"/>
      <opf:item href="images/28-F07.tif.jpg" id="d64e7" media-type="image/jpeg"/>
      <opf:item href="images/20-W01-cover.jpg" id="cover-image" media-type="image/jpeg"/>
      <opf:item href="images/23-F02.tif.jpg" id="d64e11" media-type="image/jpeg"/>
      <opf:item href="images/26-F05.tif.jpg" id="d64e14" media-type="image/jpeg"/>
      <opf:item href="images/31-F10.tif.jpg" id="d64e16" media-type="image/jpeg"/>
      <opf:item href="images/24-F03.tif.jpg" id="d64e18" media-type="image/jpeg"/>
      <opf:item href="images/21-logo_tm.tif.png" id="d64e20" media-type="image/png"/>
      <opf:item href="images/30-F09.tif.jpg" id="d64e22" media-type="image/jpeg"/>
      <opf:item href="images/29-F08.tif.jpg" id="d64e24" media-type="image/jpeg"/>
      <opf:item href="images/22-F01.tif.jpg" id="d64e27" media-type="image/jpeg"/>
   </opf:manifest>
   <opf:spine toc="ncx">
      <opf:itemref idref="cover"/>
      <opf:itemref idref="frontmatter"/>
      <opf:itemref idref="d44e9"/>
      <opf:itemref idref="d44e11"/>
      <opf:itemref idref="d44e13"/>
      <opf:itemref idref="d44e16"/>
      <opf:itemref idref="d44e18"/>
      <opf:itemref idref="d44e20"/>
      <opf:itemref idref="d44e22"/>
      <opf:itemref idref="d44e24"/>
      <opf:itemref idref="d44e26"/>
      <opf:itemref idref="d44e29"/>
      <opf:itemref idref="d44e31"/>
      <opf:itemref idref="d44e33"/>
      <opf:itemref idref="d44e35"/>
      <opf:itemref idref="d44e37"/>
      <opf:itemref idref="d44e39"/>
      <opf:itemref idref="d44e42"/>
      <opf:itemref idref="d44e43"/>
   </opf:spine>
   <opf:guide>
      <opf:reference href="1-A01-Rowman_cover.xhtml" title="Cover" type="cover"/>
   </opf:guide>
</opf:package>

`

**Comment by mertakdut** [comment]
I'll do the tests needed and will try to find the best solution possible.
