### ISSUE TITLE
Entire Book Content Length

### ISSUE THREAD

**Issue by sethchhim** [mertakdut/EpubParser#23]
I'm looking for a way to get the total size of a book so I can create a simple progress dialog. Here is what I have tried but it is painfully inefficient and slow:

```
private int getBookContentLength() {
        int count = 0;
        try {
            for (int i = 0; i < Integer.MAX_VALUE; i++) {
                count = count + reader.readSection(i).getSectionContent().length();
            }
        } catch (OutOfPagesException e) {
            return count;
        } catch (ReadingException e) {
            e.printStackTrace();
        }
        return count;
    }
```

Do you plan on implementing something similar or do you know of a better way? Thanks.

**Comment by mertakdut** [comment]
Hello,

Quoting from README file.

> EpubParser lets you read the epub content page by page. It aims to reduce memory consumption. It is useful for large epub files.

The whole purpose of this library is not "knowing" the whole book content. It parses the book as you progress in book.

Your solution removes the distinction of this library from other epub libraries. And yes, currently there is no other solutions.

I'll think of a solution as there are many requests. However, keep in mind that we may only _guess_ the total size of the book. Which means there may never be a real  "getting total size of a book" solution.

Good day.

**Comment by sethchhim** [comment]
Your reply makes sense, thanks for that. I can work around this limitation because the loading times are ridiculously fast.
