### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by Jon6193** [mertakdut/EpubParser#4]
Do you have a sample using this library?

**Comment by mertakdut** [comment]
Not yet. An android application will soon be published. I'll drop the link.

**Comment by Erbolat** [comment]
please give the link sample in android application

**Comment by verdayilmaz** [comment]
Mert bu nedir?

22 Tem 2016 09:55 tarihinde "Yerbolat" <notifications@github.com> yazdı:

**Comment by mertakdut** [comment]
https://github.com/mertakdut/EpubParser-Sample-Android-Application
