### ISSUE TITLE
Omit Title

### ISSUE THREAD

**Issue by sethchhim** [mertakdut/EpubParser#9]
Is there any way I can omit the title from getSectionContent() ?

I think it would be better if the title was optional or removed entirely to provide a more immersive reading experience.
Love your work, very useful and really great!

**Comment by mertakdut** [comment]
Hi,

Added the needed parameter **isOmittingTitleTag**. We'll be able to use it on 1.0.84 :)

**Comment by sethchhim** [comment]
The new feature works wonderful, thank you very much.
